# Generated by Django 4.2.4 on 2023-08-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_home_name_home_mainpara_home_paragraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='mainpara',
            field=models.CharField(default='Main Paragraph', max_length=300),
        ),
        migrations.AlterField(
            model_name='home',
            name='paragraph',
            field=models.CharField(default='Paragraph', max_length=300),
        ),
        migrations.AlterField(
            model_name='home',
            name='pricing',
            field=models.CharField(default='Pricing', max_length=250),
        ),
        migrations.AlterField(
            model_name='home',
            name='servicespara',
            field=models.CharField(default='Serivices Description', max_length=300),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
