# Generated by Django 4.2.4 on 2023-08-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_home_mainpara_alter_home_paragraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='servicespara',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
