# Generated by Django 4.2.4 on 2023-08-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_home_servicespara'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceimage', models.ImageField(blank=True, upload_to='images/')),
                ('servicetitle', models.CharField(blank=True, max_length=40)),
                ('serviceparagraphtwo', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='home',
            old_name='servicesimg',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='servicespara',
            new_name='maintitle',
        ),
        migrations.RemoveField(
            model_name='home',
            name='pricing',
        ),
        migrations.AlterField(
            model_name='home',
            name='mainpara',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='home',
            name='paragraph',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
