# Generated by Django 4.2.4 on 2023-08-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_services_rename_servicesimg_home_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('aboutimage', models.ImageField(blank=True, upload_to='images/')),
                ('aboutpara', models.TextField()),
            ],
        ),
    ]
